"""Task Brief Builder for Human & Remote Silicon Worker UX Cohesion.

Parses OpenOPC task specifications, project goals, role assignments, and upstream
DAG subagent deliverables into a clean, comprehensive markdown task brief.
"""

from __future__ import annotations

from typing import Any


class TaskBriefBuilder:
    """Compiles task specifications and DAG context into a structured markdown document."""

    @staticmethod
    def build_markdown_brief(
        task_id: str,
        title: str,
        description: str,
        role: str,
        priority: int = 5,
        project_id: str = "default",
        metadata: dict[str, Any] | None = None,
        upstream_deliverables: list[dict[str, Any]] | None = None,
    ) -> str:
        """Format a complete, human-readable markdown brief."""
        meta = metadata or {}
        project_goal = meta.get("project_goal") or meta.get("goal") or "Execute OpenOPC agentic workflow step."
        work_item_id = meta.get("work_item_id") or meta.get("wi_id") or ""
        instructions = meta.get("instructions") or meta.get("prompt") or description

        sections: list[str] = []

        # Header
        sections.append(f"# Task Brief: {title or task_id}")
        sections.append(
            f"**Task ID:** `{task_id}` | **Assigned Role:** `{role or 'Unassigned'}` | **Priority:** {priority}/10\n"
        )

        # Overarching Project Context
        sections.append("## 🎯 Overarching Project Context")
        sections.append(f"**Project ID:** `{project_id}`")
        if work_item_id:
            sections.append(f"**Delegation Work Item:** `{work_item_id}`")
        sections.append(f"**Goal:** {project_goal}\n")

        # Specific Task Objective
        sections.append("## 📋 Specific Task Objective")
        if instructions:
            sections.append(instructions.strip())
        else:
            sections.append("Complete assigned task objective and submit deliverable text or file attachments.")
        sections.append("")

        # Upstream Dependencies & Artifacts
        if upstream_deliverables:
            sections.append("## 🔗 Upstream Subagent Context & Artifacts")
            sections.append("The following deliverables were generated by upstream AI agents or predecessor tasks:\n")
            for idx, item in enumerate(upstream_deliverables, 1):
                anc_role = item.get("role") or "Upstream Agent"
                anc_task = item.get("opc_task_id") or f"Step {idx}"
                anc_text = item.get("deliverable_text") or "No text provided."
                sections.append(f"### {idx}. [{anc_role}] (Task: `{anc_task}`)")
                sections.append(f"```text\n{anc_text.strip()}\n```")
                artifacts = item.get("artifacts") or []
                if artifacts:
                    sections.append("**Attached Artifacts:**")
                    for art in artifacts:
                        filename = art.get("original_filename") or "artifact"
                        url = art.get("download_url") or "#"
                        sections.append(f"- [{filename}]({url}) ({art.get('file_size_bytes', 0)} bytes)")
                sections.append("")

        # Instructions for Contractor / Worker
        sections.append("## ✍️ Contractor / Worker Instructions")
        sections.append(
            "1. Review the objective and upstream deliverables above.\n"
            "2. Execute the required work (code diff, technical document, or analysis).\n"
            "3. Submit your final deliverable via this portal or API to instantly unblock the OpenOPC DAG."
        )

        return "\n".join(sections)
